title: PumpLogix
description: >-
  Smart oil well pump testing and data management platform. Streamline operations
  with real-time monitoring, powerful analytics, and comprehensive reporting.
url: "https://pumplogix.app"
baseurl: ""
app_url: "https://pump-logix-app.fly.dev"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
